project 'PokeRadar.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'PokeRadar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeRadar
  
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
